---
- name: Create backup script directory
  file:
    path: "{{ backup_script_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - backup
    - backup-create-backup-script-directory
    - webserver
    - appserver
    - dbserver

- name: Configure a backup script
  template:
    src: "{{ backup_script_path.lstrip('/') }}.j2"
    dest: "{{ backup_script_path }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - backup
    - backup-configure-script
    - webserver
    - appserver
    - dbserver

- name: Download a dir backup script from github
  git:
    repo: "{{ dir_backup_repo }}"
    dest: "{{ dir_backup_dest }}"
    version: "{{ dir_backup_version }}"
  tags:
    - backup
    - backup-download-dir-backup-script
    - webserver
    - appserver
    - dbserver

- name: Check the dir backup script exists
  stat:
    path: "{{ dir_backup_dest.rstrip('/') }}/{{ dir_backup_file }}"
  register: dir_backup
  tags:
    - backup
    - backup-check-dir-backup-script-exists
    - webserver
    - appserver
    - dbserver

- name: Copy a dir backup script
  copy:
    remote_src: yes
    src: "{{ dir_backup_dest.rstrip('/') }}/{{ dir_backup_file }}"
    dest: "{{ backup_script_dir.rstrip('/') }}/{{ dir_backup_file }}"
    owner: root
    group: root
    mode: 0755
  when: dir_backup.stat.exists
  tags:
    - backup
    - backup-copy-dir-backup-script
    - webserver
    - appserver
    - dbserver

# Reference: https://opensource.com/article/20/7/systemd-timers
- name: Create backup services
  template:
    src: "{{ item.lstrip('/') }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ backup_service_path }}"
    - "{{ backup_timer_path }}"
  tags:
    - backup
    - backup-create-backup-services
    - webserver
    - appserver
    - dbserver
